spring:
  application:
    name: tour-service
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info

external:
  api:
    visit:
      url: https://apis.data.go.kr/B551011/KorService2/
      key: "2b60ac0937d652ae50c8eb032557ed1fce11654082e0627acf0e7f450861867e"
      endpoint:
        location: locationBasedList2
        area: areaBasedList2
        keyword: searchKeyword2
        intro: detailIntro2
        detail: detailCommon2
        image: detailImage2
        ldong: ldongCode2
        lcls: lclsSystmCode2
    
    parking:
      url: https://api.data.go.kr/openapi/
      key: "2b60ac0937d652ae50c8eb032557ed1fce11654082e0627acf0e7f450861867e"
      endpoint:
        list: tn_pubr_prkplce_info_api
      